version: '3'
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "testedb"
    volumes:
      - "/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
